### ISSUE TITLE
Installation fails with package not found

### ISSUE THREAD

**Issue by chbndrhnns** [FriendlyUser/vuepress-theme-cool#1]
The second step in your instructions fails for me:

`yarn add -D vuepress-cooltheme` gives me

`error An unexpected error occurred: "https://registry.yarnpkg.com/vuepress-cooltheme: Not found".`

**Comment by FriendlyUser** [comment]
The standard naming format of vuepress themes is `vuepress-theme-<name of theme>`.

The command `yarn add -D vuepress-theme-cool` should work.

That was a typo on my part, I will update the documentation when I have time.

**Comment by chbndrhnns** [comment]
Did not know about the default naming - otherwise I would have figured that out for myself. Thanks!
