### ISSUE TITLE
fail to install after adding this package with version "^1.3.0"

### ISSUE THREAD

**Issue by franklinqin0** [FriendlyUser/vuepress-theme-cool#13]
"yarn dev" is successful, but webpage doesn't show anything. I opened console and saw the following error info:

> index.js?5156:3
    Uncaught ReferenceError: global is not defined
    at eval (index.js?5156:3)
    at Object../node_modules/has-symbols/index.js (app.js:3156)
    at __webpack_require__ (app.js:769)
    at fn (app.js:130)
    at eval (GetIntrinsic.js?e9ac:39)
    at Object../node_modules/es-abstract/GetIntrinsic.js (app.js:3108)
    at __webpack_require__ (app.js:769)
    at fn (app.js:130)
    at eval (callBind.js?44b7:5)
    at Object../node_modules/es-abstract/helpers/callBind.js (app.js:3120)

**Comment by FriendlyUser** [comment]
What version of vuepress are you using?

The starter theme was built successfully with version `1.3.0`.

If you accidently read the section about v0 config that would be why it isn't working, but I need more details in order to debug this issue.


Possibly related to https://github.com/vuejs/vuepress/issues/1434

The latest build seemed fine with version `1.3.0`

https://travis-ci.org/FriendlyUser/vuepress-theme-cool-starter/builds/653035142

**Comment by franklinqin0** [comment]
The answer by ulivz was:
> You're using a node module at client code...

First of all, I don't think this applies to my case. I haven't used file-saver.
Second, I should apologize for unclarity of my question. This is how to reproduce the error:

1. `git clone https://github.com/FriendlyUser/vuepress-theme-cool-starter.git`
2. `yarn install`
3. `yarn dev`
4. open the corresponding url in Chrome: `http://localhost:8080/vuepress-theme-cool-starter/` in my case
5. right click `inspect` and go into console
6. saw the error `Uncaught ReferenceError: global is not defined`

I don't know if I should post this question in this project or in [cool starter](https://github.com/FriendlyUser/vuepress-theme-cool-starter), but I think the error in building cool starter originated from here.

**Comment by FriendlyUser** [comment]
I see, it could be that vuepress version 0.X.X is installed globally instead of version 1.X.X.

Have you tried running `yarn add -D vuepress` and `npx vuepress dev docs`?

**Comment by franklinqin0** [comment]
Thank you, it works!

**Comment by franklinqin0** [comment]
Problem solved. Vuepress up to date globally but should've done `npx vuepress dev docs` instead
