### ISSUE TITLE
Allow for default plantuml notation

### ISSUE THREAD

**Issue by chbndrhnns** [FriendlyUser/vuepress-theme-cool#5]
Hi,

could we allow a default plantuml notation like it is recognized by Gitlab, for example?

Then it would look like this:

```
` ` `plantuml
@startuml

@enduml
` ` `
```

If I understand it correctly, for now a PLantuml diagram is not recognized if there are three backticks before and after the start/close tags

**Comment by FriendlyUser** [comment]
I can look into that, should definitely be possibly in the upcoming 1.x version of vuepress.

To give more background information, it is a matter of being able to configuration markdown-it plugins within the vuepress configuration.

**Comment by FriendlyUser** [comment]
In order to allow for default plantuml notation, you can add options to the configuration file. `.vuepress/config.js`
```
markdown: {
    // options for markdown-it-anchor
    anchor: { permalink: true },
    // options for markdown-it-toc
    toc: { includeLevel: [1, 2,3, 4] },
    config: md => {
      // use more markdown-it plugins!
      md.set({html: true})
      md.use(require("markdown-it-katex"));
      md.use(require('markdown-it-task-lists'));
     md.use(require("markdown-it-plantuml"),{openMarker: '```plantuml', closeMarker: '```'});
      md.use(require("markdown-it-admonition"));
      // use for easy syntax mermaid diagrams
 
    }
  }
```

In order to customize markdown-it plugins add options to the statement, see [markdown-it-plantuml](https://www.npmjs.com/package/markdown-it-plantuml)

**Comment by chbndrhnns** [comment]
@FriendlyUser Have you tried this yourself? At least for me, using any custom markers does not seem to have an effect. I am still using using vuepress 0.x.

**Comment by FriendlyUser** [comment]
Lol i made a mistake, it would work for
```
` ` `plantuml
 uml goes here
` ` `
```

and not 

```
` ` `plantuml
@startuml

uml goes here
@enduml
` ` `
```

This approach worked for generating the plantuml image below

```
` ` `plantuml

rectangle "Accountability"  {
 rectangle "Risk Framing and Analyze"  as src2
 rectangle "Controls Assessment"  as tgt2
 rectangle "Risk Decision Making" as moc2
 rectangle "Resdual Signoff" as moc3
 rectangle "Risk Monitoring" as moc4
 src2 -> tgt2
 tgt2 ..> moc2
 moc2 -> moc3
 moc3 ..> moc4
}

` ` `
```

Perhaps i misunderstood the question. But yes it worked when i tried it. Also applying this change to each project and not the general theme is advisable.
